### ISSUE TITLE
Purpose of this project

### ISSUE THREAD

**Issue by SichangHe** [SRv6d/rpsl-parser#36]
Hello there, I see that you parse whois response into objects composed of attribute-value pairs. Could you explain what this project is for?

For context, in our project, we parse RPSL to extract each AS's policies.

**Comment by SRv6d** [comment]
The purpose for the time being is to reliably and efficiently parse RPSL into attribute value pairs, without interpreting them as objects for now. In the future things like routing policy might be parsed as well, but I cannot give you a timeline for that. Could this be more clear in the docs?

**Comment by SichangHe** [comment]
I think this purpose is clear and your docs is fine.

What is the deeper reason you are doing this, though? Why do you need attribute value pairs?

**Comment by SRv6d** [comment]
It is currently used in automations that are not open source, feel free to email me(in my profile) to discuss this further, closing this for now.
